### ISSUE TITLE
setup.py should not import the project, as this breaks installs via pip.

### ISSUE THREAD

**Issue by djm** [cnu/scrapy-random-useragent#2]
Given a requirements file, `requirements.txt`:

```
scrapy
scrapy-random-useragent
```

and the command:

```
pip install -r requirements.txt
```
results in the error:

```
ImportError: No module named scrapy
```

The installation of the requirements fails, as `scrapy-random-useragent` is relying on `scrapy` at a point where it has not been installed yet. This is because the `setup.py` gets read by pip, which in turn imports the project (`import random_useragent`) which in turn tries to import modules from `scrapy`, which is not yet installed, hence the `ImportError`.

This needs to be solved by removing [the import in setup.py](https://github.com/cnu/scrapy-random-useragent/blob/master/setup.py#L7) and any reliance on the data it imports.

A lot of projects just copy and paste the data, and bump both version numbers on doing a new release. However, [reading this thread](ImportError: No module named scrapy) seems like another way to handle the situation and keep things DRY.

If you wish, I can submit a PR which follows the path you wish to take the fix this - I'd just like your OK before I invest the time to do so.

Thanks,
Darian

**Comment by djm** [comment]
For users looking for a fix in the meantime, the stop gap solution is to:

```
pip install scrapy==<your.version> && pip install -r requirements.txt
```

**Comment by djm** [comment]
@cnu ping?

**Comment by cnu** [comment]
@djm It would be great if you could do a PR for this.

**Comment by djm** [comment]
Amazing, I will get on that tomorrow. Thanks.

**Comment by djm** [comment]
Closing in favour of PR #3
